version: '3'

services:
  # Serviço que irá rodar o node
  node:
    # Imagem do container
    image: node:18.12
    # Nome do container para facilitar execução
    container_name: orange_api
    # Mesmo que `docker run -t`
    tty: true
    # Mesmo que `docker run -i`
    stdin_open: true
    # Substitui o comando padrão da imagem do node
    command: bash
    # Restarta a imagem caso algo a faça parar
    restart: always
    # Diretório padrão de execução
    working_dir: /app
    # Lista de volumes (diretórios) mapeados de fora para dentro do container
    volumes:
      # Monta o diretório atual, com todos os dados do projeto,
      # dentro do diretório /app
      - ./:/app
    # Lista de serviços do qual este serviço depende
    depends_on:
      # Precisa do banco funcionando antes de subir o node
      - db
    # Lista de portas mapeadas de dentro para fora do container
    # na notação porta_de_fora:porta_de_dentro
    ports:
      # Expõe a porta padrão da aplicação:
      - 3001:3001
    # Configura as variáveis de ambiente dentro do container
    environment:
      MYSQL_HOST: db # Nome do service logo abaixo
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      PORT: 3001
      NODE_ENV: 'development'
      JWT_SECRET: 'segredo'
    networks:
      - orange_api_net

  # Serviço que irá rodar o banco de dados
  db:
    container_name: orange_db
    image: mysql:8.0.31
    # Indica de forma fixa a plataforma na qual o banco irá rodar
    platform: linux/x86_64
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
    networks:
      - orange_api_net

# Lista de redes que os containeres irão utilizar
networks:
  # Cria rede com nome `blogs_api_net`
  orange_api_net:
    # Define o `driver` como `bridge`, que é o driver padrão do docker
    driver: bridge
# As chaves `tty`, `stdin_open` e `command` fazem com que o container fique
# rodando em segundo plano, bem como tornam possível o uso do comando
# `docker attach`, já deixando o terminal atual acoplado ao container, direto
# no bash. Apesar disso, utilizar o attach mais de uma vez irá replicar o
# terminal, portanto é melhor utilizar o comando `docker exec`.
