name: 'Main'
on: pull_request
jobs:
  lint-and-tests:
    name: Run linter and then tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'
      - name: Install dependencies
        run: npm install
      - name: Run ESLint
        run: npm run lint

      - name: Run Tests
        uses: samin/mysql-action@v1
        with:
          host port: 3306
          container port: 3306
          mysql version: '8.0.31'
          mysql database: 'orangedb_test'
          mysql root password: 'root'
          mysql user: 'root'
          mysql password: 'root'
        
        run: npm start
        run: npm test
        env:
          CI: true
